### ISSUE TITLE
do u have new example also???

### ISSUE THREAD

**Issue by ashrafalzyoud** [sk-ys/redmine-view-customize-scripts#1]

**Comment by sk-ys** [comment]
Do you have any ideas?

**Comment by ashrafalzyoud** [comment]
if u can help about choose which tracker its main tracker and subtask only when im added subtask
like exaple
if tracker 1 subtask only tracker 2
if tracker 3 subtask only tracker 4
if tracker 5 subtasak only tracker 6 or tracker 7
this mean when user add issues only parent tracker (1,3,5) and what he chose will available tracker
